version: "3"

services: 
    mongodb:
        image: 'mongo'

        restart: always

        ports: 
            - 8081:8081

        volumes:
                - /home/no/mongodb/database:/data/db
        environment:
                - PUID=1000
                - PGID=1000